server {
    listen 80;
    server_name portfolio-web-i8rl.onrender.com www.portfolio-web-i8rl.onrender.com;

    root /var/www/html/public; 
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;  # Vérifie que ce chemin est correct
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    error_page 404 /index.php;

    location ~ /\.ht {
        deny all;
    }
}
