server {
    listen 80;
    server_name portfolio-web-i8rl.onrender.com;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~* \.(?:css|js|gif|png|jpg|jpeg|svg|woff|woff2|eot|ttf|otf|ico)$ {
        expires 6M;
        access_log off;
    }

    error_page 404 /index.php;
}
